# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/ActuatorState.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/BalanceState.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/DbusData.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/ChassisCmd.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/ShootCmd.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/GimbalCmd.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/GimbalDesError.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/Referee.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/LpData.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/KalmanData.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/MovingAverageData.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/SuperCapacitor.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/TofSensor.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/CapacityData.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/CommandSender.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/GameStatus.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/GameRobotStatus.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/detection/TargetDetection.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/detection/TargetDetectionArray.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/detection/TrackData.msg;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/detection/TrackDataArray.msg;/home/yuchen/usetest/RM_ROS/src/remote_devel/devel/share/rm_msgs/msg/EngineerAction.msg;/home/yuchen/usetest/RM_ROS/src/remote_devel/devel/share/rm_msgs/msg/EngineerActionGoal.msg;/home/yuchen/usetest/RM_ROS/src/remote_devel/devel/share/rm_msgs/msg/EngineerActionResult.msg;/home/yuchen/usetest/RM_ROS/src/remote_devel/devel/share/rm_msgs/msg/EngineerActionFeedback.msg;/home/yuchen/usetest/RM_ROS/src/remote_devel/devel/share/rm_msgs/msg/EngineerGoal.msg;/home/yuchen/usetest/RM_ROS/src/remote_devel/devel/share/rm_msgs/msg/EngineerResult.msg;/home/yuchen/usetest/RM_ROS/src/remote_devel/devel/share/rm_msgs/msg/EngineerFeedback.msg"
services_str = "/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/srv/ContinousDetectorSwitch.srv;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/srv/StatusChange.srv;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/srv/CameraStatus.srv"
pkg_name = "rm_msgs"
dependencies_str = "std_msgs;geometry_msgs;actionlib_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "rm_msgs;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg;rm_msgs;/home/yuchen/usetest/RM_ROS/src/rm_control/rm_msgs/msg/detection;rm_msgs;/home/yuchen/usetest/RM_ROS/src/remote_devel/devel/share/rm_msgs/msg;std_msgs;/opt/ros/noetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/noetic/share/geometry_msgs/cmake/../msg;actionlib_msgs;/opt/ros/noetic/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/noetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
