set(_CATKIN_CURRENT_PACKAGE "rm_shooter_controllers")
set(rm_shooter_controllers_VERSION "0.1.2")
set(rm_shooter_controllers_MAINTAINER "Qiayuan Liao <liaoqiayuan@gmail.com>")
set(rm_shooter_controllers_PACKAGE_FORMAT "2")
set(rm_shooter_controllers_BUILD_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "forward_command_controller" "realtime_tools" "control_toolbox" "effort_controllers" "dynamic_reconfigure")
set(rm_shooter_controllers_BUILD_EXPORT_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "forward_command_controller" "realtime_tools" "control_toolbox" "effort_controllers" "dynamic_reconfigure")
set(rm_shooter_controllers_BUILDTOOL_DEPENDS "catkin")
set(rm_shooter_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(rm_shooter_controllers_EXEC_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "forward_command_controller" "realtime_tools" "control_toolbox" "effort_controllers" "dynamic_reconfigure")
set(rm_shooter_controllers_RUN_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "forward_command_controller" "realtime_tools" "control_toolbox" "effort_controllers" "dynamic_reconfigure")
set(rm_shooter_controllers_TEST_DEPENDS )
set(rm_shooter_controllers_DOC_DEPENDS )
set(rm_shooter_controllers_URL_WEBSITE "")
set(rm_shooter_controllers_URL_BUGTRACKER "")
set(rm_shooter_controllers_URL_REPOSITORY "")
set(rm_shooter_controllers_DEPRECATED "")