set(_CATKIN_CURRENT_PACKAGE "rm_controllers")
set(rm_controllers_VERSION "0.1.2")
set(rm_controllers_MAINTAINER "Qiayuan Liao <liaoqiayuan@gmail.com>")
set(rm_controllers_PACKAGE_FORMAT "2")
set(rm_controllers_BUILD_DEPENDS )
set(rm_controllers_BUILD_EXPORT_DEPENDS )
set(rm_controllers_BUILDTOOL_DEPENDS "catkin")
set(rm_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(rm_controllers_EXEC_DEPENDS "robot_state_controller")
set(rm_controllers_RUN_DEPENDS "robot_state_controller")
set(rm_controllers_TEST_DEPENDS )
set(rm_controllers_DOC_DEPENDS )
set(rm_controllers_URL_WEBSITE "")
set(rm_controllers_URL_BUGTRACKER "https://github.com/rm-controls/rm_controllers/issues")
set(rm_controllers_URL_REPOSITORY "https://github.com/rm-controls/rm_controllers")
set(rm_controllers_DEPRECATED "")