set(_CATKIN_CURRENT_PACKAGE "imu_filter_controllers")
set(imu_filter_controllers_VERSION "0.1.2")
set(imu_filter_controllers_MAINTAINER "ljq <ljq@todo.todo>")
set(imu_filter_controllers_PACKAGE_FORMAT "2")
set(imu_filter_controllers_BUILD_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "imu_complementary_filter" "imu_filter_madgwick" "hardware_interface" "controller_interface" "realtime_tools")
set(imu_filter_controllers_BUILD_EXPORT_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "imu_complementary_filter" "imu_filter_madgwick" "hardware_interface" "controller_interface" "realtime_tools")
set(imu_filter_controllers_BUILDTOOL_DEPENDS "catkin")
set(imu_filter_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(imu_filter_controllers_EXEC_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "imu_complementary_filter" "imu_filter_madgwick" "hardware_interface" "controller_interface" "realtime_tools")
set(imu_filter_controllers_RUN_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "imu_complementary_filter" "imu_filter_madgwick" "hardware_interface" "controller_interface" "realtime_tools")
set(imu_filter_controllers_TEST_DEPENDS )
set(imu_filter_controllers_DOC_DEPENDS )
set(imu_filter_controllers_URL_WEBSITE "")
set(imu_filter_controllers_URL_BUGTRACKER "")
set(imu_filter_controllers_URL_REPOSITORY "")
set(imu_filter_controllers_DEPRECATED "")