set(_CATKIN_CURRENT_PACKAGE "rm_calibration_controllers")
set(rm_calibration_controllers_VERSION "0.1.2")
set(rm_calibration_controllers_MAINTAINER "Qiayuan Liao <liaoqiayuan@gmail.com>")
set(rm_calibration_controllers_PACKAGE_FORMAT "2")
set(rm_calibration_controllers_BUILD_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "realtime_tools" "effort_controllers" "control_msgs")
set(rm_calibration_controllers_BUILD_EXPORT_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "realtime_tools" "effort_controllers" "control_msgs")
set(rm_calibration_controllers_BUILDTOOL_DEPENDS "catkin")
set(rm_calibration_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(rm_calibration_controllers_EXEC_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "realtime_tools" "effort_controllers" "control_msgs")
set(rm_calibration_controllers_RUN_DEPENDS "roscpp" "roslint" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "realtime_tools" "effort_controllers" "control_msgs")
set(rm_calibration_controllers_TEST_DEPENDS )
set(rm_calibration_controllers_DOC_DEPENDS )
set(rm_calibration_controllers_URL_WEBSITE "")
set(rm_calibration_controllers_URL_BUGTRACKER "")
set(rm_calibration_controllers_URL_REPOSITORY "")
set(rm_calibration_controllers_DEPRECATED "")