set(_CATKIN_CURRENT_PACKAGE "rm_orientation_controller")
set(rm_orientation_controller_VERSION "0.1.2")
set(rm_orientation_controller_MAINTAINER "Qiayuan Liao <liaoqiayuan@gmail.com>")
set(rm_orientation_controller_PACKAGE_FORMAT "2")
set(rm_orientation_controller_BUILD_DEPENDS "roscpp" "roslint" "sensor_msgs" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "forward_command_controller" "realtime_tools" "tf2" "tf2_geometry_msgs" "angles")
set(rm_orientation_controller_BUILD_EXPORT_DEPENDS "roscpp" "roslint" "sensor_msgs" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "forward_command_controller" "realtime_tools" "tf2" "tf2_geometry_msgs" "angles")
set(rm_orientation_controller_BUILDTOOL_DEPENDS "catkin")
set(rm_orientation_controller_BUILDTOOL_EXPORT_DEPENDS )
set(rm_orientation_controller_EXEC_DEPENDS "roscpp" "roslint" "sensor_msgs" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "forward_command_controller" "realtime_tools" "tf2" "tf2_geometry_msgs" "angles")
set(rm_orientation_controller_RUN_DEPENDS "roscpp" "roslint" "sensor_msgs" "rm_msgs" "rm_common" "pluginlib" "hardware_interface" "controller_interface" "forward_command_controller" "realtime_tools" "tf2" "tf2_geometry_msgs" "angles")
set(rm_orientation_controller_TEST_DEPENDS )
set(rm_orientation_controller_DOC_DEPENDS )
set(rm_orientation_controller_URL_WEBSITE "")
set(rm_orientation_controller_URL_BUGTRACKER "")
set(rm_orientation_controller_URL_REPOSITORY "")
set(rm_orientation_controller_DEPRECATED "")