set(_CATKIN_CURRENT_PACKAGE "rm_manual")
set(rm_manual_VERSION "1.0.54")
set(rm_manual_MAINTAINER "Qiayuan Liao <liaoqiayuan@gmail.com>")
set(rm_manual_PACKAGE_FORMAT "2")
set(rm_manual_BUILD_DEPENDS "roscpp" "sensor_msgs" "roslint" "rm_msgs" "std_msgs" "nav_msgs" "actionlib" "rm_common" "tf2_geometry_msgs")
set(rm_manual_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "roslint" "rm_msgs" "std_msgs" "nav_msgs" "actionlib" "rm_common" "tf2_geometry_msgs")
set(rm_manual_BUILDTOOL_DEPENDS "catkin")
set(rm_manual_BUILDTOOL_EXPORT_DEPENDS )
set(rm_manual_EXEC_DEPENDS "roscpp" "sensor_msgs" "roslint" "rm_msgs" "std_msgs" "nav_msgs" "actionlib" "rm_common" "tf2_geometry_msgs")
set(rm_manual_RUN_DEPENDS "roscpp" "sensor_msgs" "roslint" "rm_msgs" "std_msgs" "nav_msgs" "actionlib" "rm_common" "tf2_geometry_msgs")
set(rm_manual_TEST_DEPENDS )
set(rm_manual_DOC_DEPENDS )
set(rm_manual_URL_WEBSITE "")
set(rm_manual_URL_BUGTRACKER "")
set(rm_manual_URL_REPOSITORY "")
set(rm_manual_DEPRECATED "")