ui:
  trigger_change:
    - name: "chassis"
      config: { start_position: [ 400, 750 ], size: 15, width: 2, title: "chassis: " }
    - name: "target"
      config: { start_position: [ 400, 700 ], size: 15, width: 2, title: "target:  " }
    - name: "exposure"
      config: { start_position: [ 400, 650 ], size: 15, width: 2, title: "exposure:" }
  time_change:
    - name: "capacitor"
      config: { start_position: [ 900, 100 ], size: 15, width: 2, delay: 0.5 }
  fixed:
    - name: "4.5m_str"
      config: { type: "string", size: 10, width: 1, color: "yellow",
                start_position: [ 1000, 375 ], content: "4.5" }
    - name: "5.3m_str"
      config: { type: "string", size: 10, width: 1, color: "yellow",
                start_position: [ 1000, 393 ], content: "5.3m" }
    - name: "5.3m_line"
      config: { type: "line", width: 2, color: "orange",
                start_position: [ 949, 391 ], end_position: [ 971, 391 ] }
    - name: "mid"
      config: { type: "line", width: 2, color: "yellow",
                start_position: [ 960, 302 ], end_position: [ 960, 540 ] }
  flash:
    - name: "spin"
      config: { start_position: [ 900, 750 ], size: 15, width: 2,
                color: "yellow", content: "please spin!!", delay: 0.8 }
    - name: "armor0"
      config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
    - name: "armor1"
      config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
    - name: "armor2"
      config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
    - name: "armor3"
      config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
